############# English navigation ##############
# main menu    
[[main]]
name = "Services"
URL = "service"
weight = 2

[[main]]
name = "Blog"
URL = "blog"
weight = 3

[[main]]
name = "Contact"
URL = "contact"
weight = 4

#Footer menu
[[footer]]
name = "Company History"
URL = "about"

[[footer]]
name = "About us"
URL = "about"

[[footer]]
name = "Contact us"
URL = "contact"

[[footer]]
name = "Privacy Policy"
URL = "#"