baseURL: "https://deoxy.net/"
title: Kevin Pham 
paginate: 5
theme: PaperMod
publishDir: "docs"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

privacy:
  googleAnalytics:
    disable: true

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Kevin Pham
    pgp: "/pgp"
    description: "(mis)adventures in computing"
    keywords: [Blog]
    author: Kevin Pham
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: light # dark, light, auto
    disableTypeIt: false
    disableThemeToggle: false

    mermaidDarkTheme: "%%{init: {'theme':'dark'}}%%"
    mermaidLightTheme: "%%{init: {'theme':'forest'}}%%"

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: false

    assets:
        disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: ""
        favicon16x16: ""
        favicon32x32: ""
        apple_touch_icon: ""
        safari_pinned_tab: ""

    label:
        text: "Kevin Pham"
        icon: /logo.jpg
        iconHeight: 40

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: Kevin Pham
        subtitle: "misadventures in computing"
        imageUrl: "/resources/logo.jpg"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "(mis)adventures in computing"
        Content: a technical infosec blog
        typeIt: true
        string1: "foo"
        string2: "bar"
        string2: "baz"

    socialIcons:
        - name: twitter
          url: "https://twitter.com/twi"
        - name: stackoverflow
          url: "https://stackoverflow.com"
        - name: github
          url: "https://github.com/"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: false # hide on single page

    editPost:
        URL: "https://github.com/<path_to_repo>/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: search
          name: search
          url: /search/
          weight: 10
        - identifier: archive
          name: archive
          url: /archive/
          weight: 20
        - identifier: tags
          name: tags
          url: /tags/
          weight: 30
        - identifier: contact
          name: contact
          url: https://keybase.io/deoxy
          weight: 40
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
markup:
     highlight:
         # anchorLineNos: true
         codeFences: true
         guessSyntax: true
         # lineNos: true
         style: monokai
